# Generated by Django 5.2.1 on 2025-06-01 11:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requests_count', models.PositiveIntegerField(default=0)),
                ('requests_reset_time', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='merchant_set', related_query_name='merchant', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='merchant_set', related_query_name='merchant', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'merchants',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_sms_provider', models.CharField(default='twilio', max_length=50)),
                ('preferred_email_provider', models.CharField(default='sendgrid', max_length=50)),
                ('preferred_push_provider', models.CharField(default='firebase', max_length=50)),
                ('preferred_whatsapp_provider', models.CharField(default='whatsapp_business', max_length=50)),
                ('daily_sms_limit', models.PositiveIntegerField(default=1000)),
                ('daily_email_limit', models.PositiveIntegerField(default=10000)),
                ('daily_push_limit', models.PositiveIntegerField(default=50000)),
                ('daily_whatsapp_limit', models.PositiveIntegerField(default=1000)),
                ('sms_sent_today', models.PositiveIntegerField(default=0)),
                ('email_sent_today', models.PositiveIntegerField(default=0)),
                ('push_sent_today', models.PositiveIntegerField(default=0)),
                ('whatsapp_sent_today', models.PositiveIntegerField(default=0)),
                ('usage_reset_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchant_settings',
            },
        ),
    ]
